#pragma once

//TODO: set this to glad.h not gl.h
#include <GL/gl.h>

#define CE_BLEND						 GL_BLEND
#define CE_COLOR_LOGIC_OP				 GL_COLOR_LOGIC_OP
#define CE_CULL_FACE					 GL_CULL_FACE
#define CE_DEBUG_OUTPUT					 GL_DEBUG_OUTPUT
#define CE_DEBUG_OUTPUT_SYNCHRONOUS		 GL_DEBUG_OUTPUT_SYNCHRONOUS
#define CE_DEPTH_CLAMP					 GL_DEPTH_CLAMP
#define CE_DEPTH_TEST					 GL_DEPTH_TEST
#define CE_DITHER						 GL_DITHER
#define CE_FRAMEBUFFER_SRGB				 GL_FRAMEBUFFER_SRGB
#define CE_LINE_SMOOTH					 GL_LINE_SMOOTH
#define CE_MULTISAMPLE					 GL_MULTISAMPLE
#define CE_POLYGON_OFFSET_FILL			 GL_POLYGON_OFFSET_FILL
#define CE_POLYGON_OFFSET_LINE			 GL_POLYGON_OFFSET_LINE
#define CE_POLYGON_OFFSET_POINT			 GL_POLYGON_OFFSET_POINT
#define CE_POLYGON_SMOOTH				 GL_POLYGON_SMOOTH
#define CE_PRIMITIVE_RESTART			 GL_PRIMITIVE_RESTART
#define CE_PRIMITIVE_RESTART_FIXED_INDEX GL_PRIMITIVE_RESTART_FIXED_INDEX
#define CE_RASTERIZER_DISCARD			 GL_RASTERIZER_DISCARD
#define CE_SAMPLE_ALPHA_TO_COVERAGE		 GL_SAMPLE_ALPHA_TO_COVERAGE
#define CE_SAMPLE_ALPHA_TO_ONE			 GL_SAMPLE_ALPHA_TO_ONE
#define CE_SAMPLE_COVERAGE				 GL_SAMPLE_COVERAGE
#define CE_SAMPLE_SHADING				 GL_SAMPLE_SHADING
#define CE_SAMPLE_MASK					 GL_SAMPLE_MASK
#define CE_SCISSOR_TEST					 GL_SCISSOR_TEST
#define CE_STENCIL_TEST					 GL_STENCIL_TEST
#define CE_TEXTURE_CUBE_MAP_SEAMLESS	 GL_TEXTURE_CUBE_MAP_SEAMLESS
#define CE_PROGRAM_POINT_SIZE			 GL_PROGRAM_POINT_SIZE
